.TH LIBAR2SIMPLIFIED_RECOMMENDATION 3 LIBAR2SIMPLIFIED
.SH NAME
libar2simplified_recommendation - Get recommended hashing parameters

.SH SYNOPSIS
.nf
#include <libar2simplified.h>

const char *libar2simplified_recommendation(int \fIside_channel_free\fP);
.fi
.PP
Link with
.IR "-lar2simplified" .

.SH DESCRIPTION
The
.BR libar2simplified_recommendation ()
function returns a hashing parameter string
that can be used as input to the
.BR libar2simplified_crypt (3)
and
.BR libar2simplified_decode (3)
functions.
.PP
.I side_channel_free
shall be 1 if you know that the environment
is safe enought against side-channel attacks,
otherwise it shall be 0.
.PP
The output parameters are just so you have
something to start with, they shall not be taken
too seriously, and should be tween to your
requirements.

.SH RETURN VALUES
The
.BR libar2simplified_recommendation ()
function returns a statically allocated,
read-only, hashing parameter string.

.SH ERRORS
The
.BR libar2simplified_recommendation ()
function cannot fail.

.SH SEE ALSO
.BR libar2simplified (7),
.BR libar2simplified_crypt (3),
.BR libar2simplified_decode (3),
.BR libar2_hash (3)
